package io.supabase.gotrue.domain

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @property idToken The IDToken of the user.
 * @property nonce The nonce of the user. The nonce is a random value generated by the developer (= yourself) before
 * the initial grant is started. You should check the OpenID Connect specification for details.
 * https://openid.net/developers/specs/
 * @property provider The provider of the user.
 * @property clientId The clientID of the user.
 * @property issuer The issuer of the user.
 */
@Serializable
data class OpenIDConnectCredentials(
    @SerialName("id_token") val idToken: String,
    val nonce: String,
    val provider: Provider?,
    @SerialName("client_id") val clientId: String?,
    val issuer: String?
)
